AWSTemplateFormatVersion: "2010-09-09"
Description: Glue - Database, Crawler, ETL Job, Lake Formation

Parameters:
  ProjectName:
    Type: String
  RawDataBucket:
    Type: String
  ProcessedDataBucket:
    Type: String
  GlueScriptsBucket:
    Type: String
  GlueJobRoleArn:
    Type: String
  DatabaseSecretArn:
    Type: String
    Default: ""
    Description: Database credentials secret ARN
  VpcId:
    Type: String
    Default: ""
  SubnetIds:
    Type: CommaDelimitedList
    Default: ""
  SubnetAzs:
    Type: CommaDelimitedList
    Default: ""
  GlueSecurityGroupId:
    Type: String
    Default: ""
  AlarmTopicArn:
    Type: String
    Default: ""

Conditions:
  UseVpcConfig: !Not [!Equals [!Ref VpcId, ""]]
  HasDatabaseSecret: !Not [!Equals [!Ref DatabaseSecretArn, ""]]
  HasAlarmTopic: !Not [!Equals [!Ref AlarmTopicArn, ""]]

Resources:
  # Glue database for recommendation data
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_db'
        Description: Database for music recommendation data
        LocationUri: !Sub 's3://${RawDataBucket}/'

  # VPC connection for Glue jobs
  GlueVpcConnection:
    Type: AWS::Glue::Connection
    Condition: UseVpcConfig
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Name: !Sub '${ProjectName}-glue-vpc-connection'
        ConnectionType: NETWORK
        PhysicalConnectionRequirements:
          AvailabilityZone: !Select [0, !Ref SubnetAzs]
          SubnetId: !Select [0, !Ref SubnetIds]
          SecurityGroupIdList:
          - !Ref GlueSecurityGroupId

  # Crawler for Last.fm data
  GlueCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: GlueDatabase
    Properties:
      Name: !Sub '${ProjectName}-lastfm-crawler'
      Role: !Ref GlueJobRoleArn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
        - Path: !Sub 's3://${RawDataBucket}/lastfm/raw/chunks/'
        - Path: !Sub 's3://${RawDataBucket}/lastfm/playlists/'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

  # ETL job for NeuMF data processing
  GlueETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectName}-neumf-etl'
      Description: ETL job for NeuMF training data
      Role: !Ref GlueJobRoleArn
      GlueVersion: '4.0'
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 120
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${GlueScriptsBucket}/scripts/glue_etl_neumf.py'
        PythonVersion: '3'
      DefaultArguments:
        '--job-bookmark-option': job-bookmark-enable
        '--enable-metrics': 'true'
        '--raw_data_bucket': !Ref RawDataBucket
        '--processed_data_bucket': !Ref ProcessedDataBucket
        '--database_name': !Ref GlueDatabase
        '--database_secret_arn': !If
        - HasDatabaseSecret
        - !Ref DatabaseSecretArn
        - ''
      Connections:
        Connections: !If
        - UseVpcConfig
        - - !Ref GlueVpcConnection
        - !Ref AWS::NoValue
      ExecutionProperty:
        MaxConcurrentRuns: 1

  GlueJobAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmTopic
    Properties:
      AlarmName: !Sub '${ProjectName}-glue-etl-failed'
      AlarmDescription: Alarm if Glue ETL job fails
      Namespace: Glue
      MetricName: glue.driver.aggregate.numFailedTasks
      Dimensions:
      - Name: JobName
        Value: !Ref GlueETLJob
      - Name: Type
        Value: Gauge
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - !Ref AlarmTopicArn

  # ===============================
  # Lake Formation Configuration
  # ===============================

  LakeFormationSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
      - DataLakePrincipalIdentifier: !Ref GlueJobRoleArn
      - DataLakePrincipalIdentifier: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-cloudformation-role'

  # Register raw data bucket
  LakeFormationRawDataLocation:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 'arn:aws:s3:::${RawDataBucket}'
      UseServiceLinkedRole: true

  # Register processed data bucket
  LakeFormationProcessedDataLocation:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Sub 'arn:aws:s3:::${ProcessedDataBucket}'
      UseServiceLinkedRole: true

  # Lake Formation Database Permissions
  LakeFormationDatabasePermissionV2:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties:
      Resource:
        Database:
          CatalogId: !Ref AWS::AccountId
          Name: !Ref GlueDatabase
      Principal:
        DataLakePrincipalIdentifier: !Ref GlueJobRoleArn
      Permissions:
      - ALL
      PermissionsWithGrantOption:
      - ALL

  # Lake Formation Table Permissions (Wildcard)
  LakeFormationTablePermissionV2:
    Type: AWS::LakeFormation::PrincipalPermissions
    Properties:
      Resource:
        Table:
          CatalogId: !Ref AWS::AccountId
          DatabaseName: !Ref GlueDatabase
          TableWildcard: {}
      Principal:
        DataLakePrincipalIdentifier: !Ref GlueJobRoleArn
      Permissions:
      - ALL
      PermissionsWithGrantOption:
      - ALL

  # Lake Formation Data Location Permissions (Raw Data)
  LakeFormationRawDataLocationPermissionV2:
    Type: AWS::LakeFormation::PrincipalPermissions
    DependsOn: LakeFormationRawDataLocation
    Properties:
      Resource:
        DataLocation:
          CatalogId: !Ref AWS::AccountId
          ResourceArn: !Sub 'arn:aws:s3:::${RawDataBucket}'
      Principal:
        DataLakePrincipalIdentifier: !Ref GlueJobRoleArn
      Permissions:
      - DATA_LOCATION_ACCESS
      PermissionsWithGrantOption:
      - DATA_LOCATION_ACCESS

  # Lake Formation Data Location Permissions (Processed Data)
  LakeFormationProcessedDataLocationPermissionV2:
    Type: AWS::LakeFormation::PrincipalPermissions
    DependsOn: LakeFormationProcessedDataLocation
    Properties:
      Resource:
        DataLocation:
          CatalogId: !Ref AWS::AccountId
          ResourceArn: !Sub 'arn:aws:s3:::${ProcessedDataBucket}'
      Principal:
        DataLakePrincipalIdentifier: !Ref GlueJobRoleArn
      Permissions:
      - DATA_LOCATION_ACCESS
      PermissionsWithGrantOption:
      - DATA_LOCATION_ACCESS



Outputs:
  GlueDatabaseName:
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub '${ProjectName}-GlueDatabase'
  GlueETLJobName:
    Value: !Ref GlueETLJob
    Export:
      Name: !Sub '${ProjectName}-GlueETLJob'
  GlueCrawlerName:
    Value: !Ref GlueCrawler
    Export:
      Name: !Sub '${ProjectName}-GlueCrawler'
