AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda Functions

Parameters:
  ProjectName:
    Type: String
  LambdaExecutionRoleArn:
    Type: String
  RawDataBucket:
    Type: String
  ProcessedDataBucket:
    Type: String
  UserFeaturesTable:
    Type: String
  RecommendationCacheTable:
    Type: String
  TrackMetadataTable:
    Type: String
  UserEventsStreamArn:
    Type: String
  ListenBrainzToken:
    NoEcho: true
    Type: String
    Default: ""
  VpcId:
    Type: String
    Default: ""

  SubnetIds:
    Type: CommaDelimitedList
    Default: ""
  LambdaSecurityGroupId:
    Type: String
    Default: ""
  AlarmTopicArn:
    Type: String
    Default: ""

Conditions:
  UseVpcConfig: !Not [!Equals [!Ref VpcId, ""]]
  HasAlarmTopic: !Not [!Equals [!Ref AlarmTopicArn, ""]]

Resources:
  # ListenBrainz API token secret
  ListenBrainzSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-listenbrainz-token'
      SecretString: !Sub '{"token": "${ListenBrainzToken}"}'

  # Lambda for downloading Last.fm dataset
Outputs:
  ListenBrainzSecretArn:
    Value: !Ref ListenBrainzSecret
